### ISSUE TITLE
404 in Jupyter Notebook: Missing "rest-evaluator" Role

### ISSUE THREAD

**Issue by ShonSS** [marklogic/marklogic-python-client#28]
Hi, while executing the example notebook, I encountered a specific issue with the MarkLogic 11.0.3 Management API. The code section responsible for creating a new role, intended to assign existing roles "tde-admin," "rest-evaluator," and "qconsole-user," resulted in a 404 error. Using Postman, `SEC-ROLEDNE: (err:FOER0000) Role does not exist: sec:role-name = rest-evaluator` pinpointed the absence of the rest-evaluator role in my local MarkLogic instance. This issue surfaced while working on a Mac M1, using tools such as DataSpell and PyCharm to execute the notebook. I wanted to bring it to your attention and request your advice on how to address the missing rest-evaluator role, thanks.

**Comment by rjrudin** [comment]
Thanks @ShonSS  - we'll fix that right away - we actually tested this on several machines that had the non-OOTB "rest-evaluator" role on them and thus mistakenly included it in the instructions.

**Comment by rjrudin** [comment]
@ShonSS The notebook file has been updated with the following changes:

1. The `python-blog-role` role now inherits `rest-writer` instead of the non-standard `rest-evaluator` role.
2. The cell that uses pandas also installs pandas to be certain that it can be imported. 

Let us know if it works for you now!

**Comment by ShonSS** [comment]
Progress!

Rob, thank you for your quick response and for addressing the issue with the role. I've had a chance to test the updated notebook, and everything looks good. I do have some notes:

1. I had already installed pandas, so the result in my case is 7 lines about requirements satisfied and a line about possibly restarting the kernel, followed by the output. It works fine, just thought I'd let you know in case you weren't intending that.

2. Initially, I received an unauthorized message from `/v1/search`. I noticed the code's using digest authentication, so I switched the server to that scheme. In the case basic authentication is the default, I thought it might be worth mentioning.

3. At first, I encountered a `SQL-TABLEREINDEXING` error with the Optic query. It only required a brief wait until I executed the notebook again, and so it worked as expected.

Your proactive support is much appreciated. If there's anything else I can assist with or any further testing needed, please don't hesitate to ask.

**Comment by rjrudin** [comment]
Thanks @ShonSS for the feedback - comments on each item:

1. That's fine about the notice for restarting the kernel; we're not sure yet when that would be needed but the need for doing so has not occurred in any of our testing. The command to install `pandas` is really there as a safeguard with the assumption that a Python developer knows how to get it installed one way or another. 
2. Good point, we'll add a notice to confirm that the App-Services app server on 8000 is set to digest or digestbasic, and what to do if it's set to basic.
3. That's fine too, and we'll add a note stating to just re-run the cell in case MarkLogic has not finished re-indexing.

**Comment by ShonSS** [comment]
Rob,

Understood about the pandas installation, it aligns well with common Python practices.

Good to hear about the planned notice for the authentication settings, it might be a helpful clarification.

Adding a note about re-running the cell for re-indexing is a practical touch.

I wanted to mention that I'm experimenting with ipywidgets for the notebook and Streamlit for quick prototyping using your new client. If time permits, I'd like to possibly contribute to the examples directory, for your consideration.

Additionally, I'm presently blocked by an issue with MarkLogic in which I create a new app server, but I get a 404 when trying to hit the endpoints. I've observed that the URL rewriter and error handler fields are empty, and supplying the default scripts results in a similar 404. I'll try uninstalling and reinstalling unless you have a better recommendation.

Thanks again for your responsiveness and support,
Shon

**Comment by ShonSS** [comment]
Rob, thanks for the guidance, I attempted to create a new app server for my specific database, as I want to define settings and range indexes separate from the Documents database. My intention was to manually configure the app server using the admin console's "Create HTTP" option, as I'm not planning to use scripted deployments. However, I was uncertain if my difficulties indicated a broader issue with the integrity of my local MarkLogic instance. If that isn't a concern, I'm comfortable proceeding with the ml-gradle approach.

**Comment by rjrudin** [comment]
I think the other field to check is "Rewrite Resolves Globally" - that needs to be set to true, and it defaults to false when you create an HTTP server through the Admin UI.

**Comment by ShonSS** [comment]
Success! That was exactly the last step I needed, I'll have to remember that one. Much appreciated.

**Comment by rjrudin** [comment]
Going to close this as #30 provides additional information. Feel free to use this for more conversation though.
